all:
	javac -d . main/java/peer/WatchDir.java main/java/peer/ClientDriver.java main/java/peer/PeerInt.java main/java/peer/PeerImpl.java main/java/peer/Client.java main/java/host/ServerImpl.java main/java/host/IndexInt.java

clean:
	rm ./main/java/*/*~ ./main/java/*/*.class ./main/java/*/#*#
